version: 2.1  # Specify the version of the configuration file.

orbs:
  docker: circleci/docker@2.2.0  # Declare the Docker orb and its version.

jobs:
  lint-dockerfile:  # Define a job for linting the Dockerfile.
    executor: docker/hadolint  # Use the docker/hadolint executor.
    steps:
      - checkout  # Fetch the source code.
      - docker/hadolint:  # Run Hadolint on the Dockerfile.
          dockerfiles: Dockerfile

  test-app:  # Define a job for running application tests.
    docker:
      - image: cimg/go:1.20.4  # Use the cimg/go:1.20.4 Docker image.
    steps:
      - checkout  # Fetch the source code.
      - run: | # Execute the test command.
          go test -v -short --count=1 $(go list ./...)  

  build-app-karsajobs:  # Define a job for building and pushing a Docker image.
    executor: docker/docker  # Use the docker/docker executor.
    steps:
      - checkout  # Fetch the source code.
      - setup_remote_docker:  # Set up a remote Docker environment.
          version: default
      - run: | # Execute the shell script to build and push the Docker image.
          sh ./build_push_image_karsajobs.sh  

workflows:
  lint-dockerfile:  # Define a workflow for the lint-dockerfile job.
    jobs:
      - lint-dockerfile

  test-app:  # Define a workflow for the test-app job.
    jobs:
      - test-app

  build-app-karsajobs:  # Define a workflow for the build-app-karsajobs job.
    jobs:
      - build-app-karsajobs