apiVersion: v1  # Specify the Kubernetes API version for the Service
kind: Service  # Specify the resource kind as Service
metadata:
  name: karsajobs-ui  # Specify the name of the Service
  labels:
    app: karsajobs  # Labels for the Service
spec:
  ports:
    - port: 8000  # Specify the port on the Service
  selector:
    tier: frontend  # Match labels to target the pods
