apiVersion: apps/v1  # Specify the Kubernetes API version for the Deployment
kind: Deployment  # Specify the resource kind as Deployment
metadata:
  name: karsajobs  # Specify the name of the Deployment
  labels:
    app: karsajobs  # Labels for the Deployment
    tier: backend
spec:
  replicas: 1  # Set the number of desired replicas
  selector:
    matchLabels:
      tier: backend  # Match labels to target the pods
  template:
    metadata:
      labels:
        app: karsajobs  # Labels for pods created by the Deployment
        tier: backend
    spec:
      containers:
        - name: karsajobs  # Specify the name of the container
          image: ghcr.io/raassh-23/karsajobs:latest  # Set the image for the container
          ports:
            - containerPort: 8080  # Specify the container port to expose
          env:
            - name: APP_PORT  # Set environment variable APP_PORT
              value: 8080
            - name: MONGO_HOST  # Set environment variable MONGO_HOST using the value from MONGO_SERVICE_HOST
              value: $(MONGO_SERVICE_HOST)
            - name: MONGO_USER  # Set environment variable MONGO_USER using the value from the secretKeyRef
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_USERNAME
            - name: MONGO_PASS  # Set environment variable MONGO_PASS using the value from the secretKeyRef
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGO_ROOT_PASSWORD
