apiVersion: v1 # Specify the Kubernetes API version for the Service
kind: Service # Specify the resource kind as Service
metadata:
    name: shipping # Specify the name of the Service
    labels:
        app: shipping # Labels for the Service
        service: shipping
spec:
    ports:
        - port: 3001 # Specify the port on the Service
    selector:
        app: shipping # Match labels to target the pods
---
apiVersion: apps/v1 # Specify the Kubernetes API version for the Deployment
kind: Deployment # Specify the resource kind as Deployment
metadata:
    name: shipping # Specify the name of the Deployment
    labels:
        app: shipping # Labels for the Deployment
spec:
    replicas: 1 # Set the number of desired replicas
    selector:
        matchLabels:
            app: shipping # Match labels to target the pods
    template:
        metadata:
            labels:
                app: shipping # Labels for pods created by the Deployment
        spec:
            containers:
                - name: shipping # Specify the name of the container
                  image: ghcr.io/raassh-23/shipping-service:latest # Specify the image for the container
                  imagePullPolicy: IfNotPresent # Set the image pull policy
                  ports:
                      - containerPort: 3001 # Specify the container port to expose
                  env:
                      - name: QUEUE_HOST # Specify the environment variable for the queue host
                        valueFrom:
                            secretKeyRef:
                                name: e-commerce-queue-default-user # Specify the name of the secret
                                key: host # Specify the key for the secret value
                      - name: QUEUE_PORT # Specify the environment variable for the queue port
                        valueFrom:
                            secretKeyRef:
                                name: e-commerce-queue-default-user # Specify the name of the secret
                                key: port # Specify the key for the secret value
                      - name: QUEUE_USERNAME # Specify the environment variable for the queue username
                        valueFrom:
                            secretKeyRef:
                                name: e-commerce-queue-default-user # Specify the name of the secret
                                key: username # Specify the key for the secret value
                      - name: QUEUE_PASSWORD # Specify the environment variable for the queue password
                        valueFrom:
                            secretKeyRef:
                                name: e-commerce-queue-default-user # Specify the name of the secret
                                key: password # Specify the key for the secret value
                      - name: AMQP_URL # Specify the environment variable for the AMQP URL
                        value: "amqp://$(QUEUE_USERNAME):$(QUEUE_PASSWORD)@$(QUEUE_HOST):$(QUEUE_PORT)" # Specify the value of the environment variable
